BIN := pkg-config

.PHONY: default
default: $(BIN)

include $(ROOTDIR)/mk/cc.mk
include $(ROOTDIR)/mk/ccld.mk
include $(ROOTDIR)/mk/deps.mk
include $(ROOTDIR)/mk/clean.mk
include $(ROOTDIR)/mk/notest.mk
