DEPS := lib/cbase lib/crypto vendor/sodium vendor/fastrange

include $(ROOTDIR)/scripts/cc.mk
include $(ROOTDIR)/scripts/deps.mk
include $(ROOTDIR)/scripts/clean.mk
include $(ROOTDIR)/scripts/notest.mk
