DEPS := lib/cbase vendor/sodium vendor/ngtcp2

LOCAL_CFLAGS += -Wno-unused-parameter

include $(ROOTDIR)/mk/cc.mk
include $(ROOTDIR)/mk/test.mk
include $(ROOTDIR)/mk/deps.mk
include $(ROOTDIR)/mk/clean.mk
