DEPS := lib/cbase lib/crypto lib/base64 lib/getpass vendor/sodium

include $(ROOTDIR)/scripts/cc.mk
include $(ROOTDIR)/scripts/deps.mk
include $(ROOTDIR)/scripts/clean.mk
include $(ROOTDIR)/scripts/notest.mk
