#!/usr/bin/env sh

name=$1

rm -rf lib/$name

mkdir lib/$name
cd lib/$name
mkdir src include
cat <<EOF > include/$name.h
#pragma once

// Header
void hello(void);
EOF
cat <<EOF > src/$name.c
#include "$name.h"

// Source
void hello(void) {}
EOF

# The Makefile must use tabs
cat <<EOF > Makefile
DEPS := lib/cbase

include \$(ROOTDIR)/scripts/cc.mk
include \$(ROOTDIR)/scripts/deps.mk
include \$(ROOTDIR)/scripts/clean.mk
EOF

cat <<EOF > $name.pc
Name: $name
Version: 0.0.1
Description: <none>
Libs: -L\${prefix} -l$name
Cflags: -I\${prefix}/include
Requirez: lib/cbase
EOF
