#!/usr/bin/env sh

name=$1

rm -rf lib/$name

mkdir lib/$name
cd lib/$name
mkdir src include
cat <<EOF > include/$name.h
#pragma once

// Header
void hello(void);
EOF
cat <<EOF > src/$name.c
#include "$name.h"

// Source
void hello(void) {}
EOF

# The Makefile must use tabs
cat <<EOF > Makefile
HDRS := \$(wildcard include/*.h) \$(wildcard src/*.h)
SRCS := \$(wildcard src/*.c)
OBJS := \$(SRCS:.c=.\$(O))
DEPS := lib/cbase

lib$name.a: \$(OBJS) Makefile .deps.ok
	\$(AR) rcs \$@ \$(OBJS)
	touch .build

%.\$(O): %.c \$(HDRS) Makefile .deps.ok
	\$(CC) -c -o \$@ -Iinclude \$(CFLAGS) \$(DEPS_CFLAGS) \$<

include \$(ROOTDIR)/scripts/deps.mk
include \$(ROOTDIR)/scripts/clean.mk
EOF

cat <<EOF > $name.pc
Name: $name
Version: 0.0.1
Description: <none>
Libs: -L\${prefix} -l$name
Cflags: -I\${prefix}/include
EOF
