#!/usr/bin/env sh

flag=$1
shift

if [ -z "$ROOTDIR" ] || [ -z "$BROOT" ]
then
  echo "Must specify ROOTDIR and BROOT"
  exit 1
fi

while [ -n "$1" ]
do

dep=$1

srcdir=$ROOTDIR/$dep
builddir=$BROOT/$dep

lib=$(basename $dep)

PKG_CONFIG_PATH="$builddir:$srcdir" \
  pkg-config \
  --define-variable=src_prefix=$srcdir \
  --define-variable=build_prefix=$builddir \
  $flag $lib

for dep in $(grep Requirez: $srcdir/$lib.pc | cut -c 11-)
do
  need $flag $dep
done

shift
done
