#!/usr/bin/env sh

flag=$1
shift

while [ -n "$1" ]
do

dep=$1

srcdir=$dep
builddir=build/$dep

lib=$(basename $dep)

if [ -n "$ROOTDIR" ]
then
  srcdir=$ROOTDIR/$srcdir
  builddir=$ROOTDIR/$builddir
fi

PKG_CONFIG_PATH="$srcdir" \
  pkg-config \
  --define-variable=src_prefix=$srcdir \
  --define-variable=build_prefix=$builddir \
  $flag $lib

for dep in $(grep Requirez: $srcdir/$lib.pc | cut -c 11-)
do
  need $flag $dep
done

shift
done
