#!/usr/bin/env sh

while [ -n "$1" ]
do

dir=$1
lib=$(basename $dir)

if [ -n "$ROOTDIR" ]
then
  dir=$ROOTDIR/$dir
fi

PKG_CONFIG_PATH=$dir pkg-config --define-variable=prefix=$dir --libs $lib

shift
done
